# Generated by Django 5.0.2 on 2024-02-12 15:49

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Song Number')),
                ('index', models.IntegerField(verbose_name='Song Index')),
                ('title', models.CharField(max_length=100, verbose_name='Song Title')),
                ('body', models.TextField(verbose_name='Lyrics of the Song')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='Slug (Part of URL)')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('category', models.CharField(choices=[('A', 'స్తుతి, ఆరాధన, సిలువ ద్యానం'), ('B', 'హెచ్చరిక, దిద్దుబాటు'), ('C', 'ప్రార్థన, విజ్ఞాపన, యాచన'), ('D', 'లేఖన విలువ '), ('E', 'సేవా పిలుపు, సేవా సమర్పణ'), ('F', 'ఆధరణ, ప్రోత్సాహము'), ('G', 'యవనస్థులు'), ('H', 'సోదరీలు'), ('I', 'సువార్త సందేశం, సువార్త పిలుపు'), ('J', 'ప్రభువు రాకడ, రాకడ సిద్ధపాటు '), ('K', 'అనుబంధ కీర్తనలు')], default='A', max_length=1, verbose_name='Content Category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags (Keywords)')),
            ],
        ),
    ]
